[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_DISABLE_EDGE_IMAGES = "true"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[build]
  command = "yarn build"
  functions = "functions"
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
