[build]
  command = "yarn run build"
  publish = "out_publish"
  functions = "out_functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_DISABLE_EDGE_IMAGES = "true"
