[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_DISABLE_EDGE_IMAGES = "true"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[build]
  command = "yarn build"
  functions = "functions"
  publish = "out"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

