[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_DISABLE_EDGE_IMAGES = "true"

[build]
  command = "yarn install && yarn build"
  publish = "out"
  environment = { YARN_VERSION = "1.22.19" }
